name: Deploy
on:
  release:
    types: [published]
  push:

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Build & Publish
      uses: jerray/publish-docker-action@v1.0.5
      with:
        repository: spectacles/gateway
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        auto_tag: true
